### ISSUE TITLE
Perfect Dark Zero crashes on cutscene checkpoints when using Mousehook

### ISSUE THREAD

**Issue by S1L3NC3E** [marinesciencedude/xenia-canary-mousehook#76]
### Validation

- [x] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [x] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [x] This issue isn't for tech support (help with Xenia).
- [x] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [x] I've checked if this issue hasn't already been reported.
- [x] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

When playing Perfect Dark Zero using the Mousehook build of Xenia Canary, the game consistently crashes during cutscene checkpoints, especially when activating cinematics after defeating bosses or reaching specific locations (e.g. Level 1 – The elevator on the Hong Kong Club, or after defeating Killian - Level 3).

![Image](https://github.com/user-attachments/assets/dd72c360-5bad-49bd-9441-56f12521035e)
![Image](https://github.com/user-attachments/assets/dd5a189d-c414-413c-8feb-7f75e7788705)

The crashes do not occur on the normal Canary build without Mousehook, but Mousehook provides better aiming experience, especially for shooters. I'd like to keep using it if possible.

### Describe what should happen

The game should play through cutscenes and checkpoints without crashing, even when using Mousehook. Input from the mouse (mapped as right stick) should not interfere with scripted events.

### If applicable, provide a callstack here, especially for crashes

The log shows repeated lines just before crashing:

F> F8000008 HostPathDevice::ResolvePath(\PDZ\ASSETS\aid)
F> F8000008 HostPathDevice::ResolvePath(\PDZ\ASSETS\aid\darkcutscenes)
F> F8000008 HostPathDevice::ResolvePath(\PDZ\ASSETS\aid\darkcutscenes\level03)
F> F8000008 HostPathDevice::ResolvePath(\PDZ\ASSETS\aid\darkcutscenes\level03\mid)
F> F8000008 HostPathDevice::ResolvePath(\PDZ\ASSETS\aid\darkcutscenes\level03\mid)
i> F8000008 Added handle:F8000118 for class xe::kernel::XObject
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5
i> F8000008 xeRtlNtStatusToDosError 103 => 3E5

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/user-attachments/files/20744995/xenia.log)

**Comment by Clippy95** [comment]
I'm aware of the crash and it's possibly fixed in https://github.com/marinesciencedude/xenia-canary-mousehook/pull/63, but I just haven't had the time to work on mousehook due to focusing on other projects, there are older builds with missing camera modes support where it doesn't crashm on my fork's actions (probably out-of-date by now)

**Comment by S1L3NC3E** [comment]
Do you have a compiled version of the solution? How can I fix it by myself if not?

**Comment by Graslu** [comment]
Still happening as of #78, same error as above.

<img width="394" height="237" alt="Image" src="https://github.com/user-attachments/assets/c8e88dd7-73fe-46c1-b30d-be4d81f08dd5" />

Also Combat Simulator doesn't work, the mouse instead just emulates the joystick and moves very slowly. There's no input injection.

**Comment by Clippy95** [comment]
> Do you have a compiled version of the solution? How can I fix it by myself if not?

After re-reading it probably doesn't fix, but either ways commit https://github.com/Clippy95/xenia-canary-mousehook/commit/a5cbfb954d03530298148d88426e1d328bc6a14e is where it started crashing, and possibly the hovercraft commit, debugging this game takes a significant of time as I'd have to play it in Debug Build (which is incredibly slow) and go to the section where it crashes
